"""empty message

Revision ID: 10279519ae95
Revises: 9f61671f09e0
Create Date: 2022-08-24 19:43:54.548018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10279519ae95'
down_revision = '9f61671f09e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
